#!/usr/bin/env ruby

puts "ARGV: #{ARGV.inspect}"
puts "$0: #{$0}"
puts "$*: #{$*.inspect}"
puts "ENV['PROCESS_SPAWN_TYPE']: #{ENV['PROCESS_SPAWN_TYPE']}"

puts 'hello world'

STDOUT.flush
sleep 2
puts 'ready'
STDOUT.flush
sleep 10
