# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rspec-background-process"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakub Pastuszek"]
  s.date = "2014-09-29"
  s.description = "Cucumber steps for spawning processes and HTTP servers for API testing or lunching stub backend. This steps can pool the background processes between scenarios. Readiness checks can be performed before tests can continue."
  s.email = "jpastuszek@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rspec-background-process.rb",
    "lib/rspec-background-process/background_process.rb",
    "lib/rspec-background-process/background_process_helpers.rb",
    "lib/rspec-background-process/process_pool.rb",
    "lib/rspec-background-process/readiness_checks.rb",
    "lib/rspec-background-process/refresh_actions.rb",
    "lib/rspec-background-process/server.rb",
    "spec/background_process_spec.rb",
    "spec/features/cwd_spec.rb",
    "spec/features/dead_detection_spec.rb",
    "spec/features/exec_and_loading_spec.rb",
    "spec/features/pool_lru_spec.rb",
    "spec/features/ready_test_spec.rb",
    "spec/features/refresh_spec.rb",
    "spec/features/reuse_spec.rb",
    "spec/features/server_spec.rb",
    "spec/features/variables_replacement_spec.rb",
    "spec/process_definition_spec.rb",
    "spec/spawn_process_helper_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/test_die",
    "spec/support/test_http_server",
    "spec/support/test_process",
    "spec/support/test_slow_die"
  ]
  s.homepage = "http://github.com/jpastuszek/rspec-background-process"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Cucumber step library useful for managing background processes during testing"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<faraday>, [">= 0.8"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<daemon>, ["~> 1.2"])
      s.add_development_dependency(%q<micromachine>, ["~> 1.1"])
      s.add_development_dependency(%q<rufus-lru>, ["~> 1.0"])
      s.add_development_dependency(%q<file-tail>, ["~> 1.0"])
      s.add_development_dependency(%q<retries>, ["~> 0.0.5"])
    else
      s.add_dependency(%q<faraday>, [">= 0.8"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<daemon>, ["~> 1.2"])
      s.add_dependency(%q<micromachine>, ["~> 1.1"])
      s.add_dependency(%q<rufus-lru>, ["~> 1.0"])
      s.add_dependency(%q<file-tail>, ["~> 1.0"])
      s.add_dependency(%q<retries>, ["~> 0.0.5"])
    end
  else
    s.add_dependency(%q<faraday>, [">= 0.8"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<daemon>, ["~> 1.2"])
    s.add_dependency(%q<micromachine>, ["~> 1.1"])
    s.add_dependency(%q<rufus-lru>, ["~> 1.0"])
    s.add_dependency(%q<file-tail>, ["~> 1.0"])
    s.add_dependency(%q<retries>, ["~> 0.0.5"])
  end
end

