#!/usr/bin/env ruby

require "webrick"

puts "ARGV: #{ARGV.inspect}"

port = ARGV.grep(/localhost:/).first.split(':', 2).last rescue 1234
puts "listening on port: #{port}"

server = WEBrick::HTTPServer.new(:Port => port)

server.mount_proc '/health_check' do |req, res|
	puts 'got health_check request'
	res.body = "OK\n\r"
end

trap("INT") {
	server.shutdown
}

trap("TERM") {
	server.shutdown
}

puts "starting"

server.start

