Feature: Managing current working directory
	Current working directory for the process by default is autogenerated temporary directory that is unique for process definition life time.

	Background:
		Given test background process executable is features/support/test_process
		And test process is ready when log file contains hello world
		Given test2 background process executable is features/support/test_process
		And test2 process is ready when log file contains hello world

	@cwd
	Scenario: By default process is started in unique temporary directory
		Given fresh test process is running and ready
		When we remember test process reported current directory
		Given fresh test2 process is running and ready
		Then remembered process current directory is different from test2 process reported one

	@cwd
	Scenario: Process current directory changes does not affect our test current directory
		Given we remember current working directory
		And fresh test process is running and ready
		Then current working directory is unchanged

	@cwd
	Scenario: Process current working directory configurable to current working directory
		Given we remember current working directory
		Given test process working directory is the same as current working directory
		Given fresh test process is running and ready
		Then current working directory is unchanged
		Then test process reports it's current working directory to be the same as current directory

	@cwd
	Scenario: The current working directory should be configurable to provided directory
		Given test process working directory is changed to tmp/test
		Given fresh test process is running and ready
		Then test process reports it's current working directory to be relative to current working directory by tmp/test

